[package]
name = "hoot"
version = "0.1.0"
edition = "2021"

[features]
default = []
std = []

[dependencies]
httparse = { version = "1.8.0", default-features = false }

[dev-dependencies]
memoffset = "0.9.0"
