[package]
name = "hoot"
version = "0.1.0"
edition = "2021"

[features]
default = []
all = ["std"]
std = []

[dependencies]
httparse = { version = "1.8.0", default-features = false }

[dev-dependencies]
memoffset = "0.9.0"

[package.metadata.docs.rs]
features = "all"
rustdoc-args = ["--cfg", "docsrs"]
