[package]
name = "hootbin"
version = "0.1.0"
edition = "2021"
authors = ["Martin Algesten <martin@algesten.se>"]
description = "hoot based library to emulate httpbin"
keywords = ["http", "server", "web"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/algesten/hoot"

[dependencies]
fastrand = "2.0.1"
hoot = { path = "..", version = "0.1.2", features = ["std"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.111"
thiserror = "1.0.56"
